FROM geoffyoon/pyflink:latest

MAINTAINER yoon, koock <deep-learning@kakao.com>

COPY ./ /root/DE-middle/flink/consumer/

WORKDIR /root/DE-middle/flink/consumer/

RUN pip3 install jupyter

RUN jupyter notebook --generate-config --allow-root

RUN echo "c.NotebookApp.password = u'sha1:6a3f528eec40:6e896b6e4828f525a6e20e5411cd1c8075d68619'" >> /root/.jupyter/jupyter_notebook_config.py

EXPOSE 8889
EXPOSE 8081

CMD /flink/bulid-target/bin/start-cluster.sh

ENTRYPOINT jupyter notebook --allow-root --ip=0.0.0.0 --port=8889 --no-browser