FROM demiddleday3_jupyter:latest

MAINTAINER yoon, koock <deep-learning@kakao.com>

COPY ./ /jupyter1

WORKDIR /jupyter1

EXPOSE 8883

ENTRYPOINT jupyter notebook --allow-root --ip=0.0.0.0 --port=8883 --no-browser