FROM demiddleday3_jupyter:latest

MAINTAINER yoon, koock <deep-learning@kakao.com>

COPY ./ /jupyter2

WORKDIR /jupyter2

EXPOSE 8884

ENTRYPOINT jupyter notebook --allow-root --ip=0.0.0.0 --port=8884 --no-browser